# -*- coding: utf-8 -*-
"""Algorithm_Study09

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_lbYyz0OihsqFQw2wUxGtp8LjeCRPrQ

##### max()을 사용하지 않고 max() 구현하기(for 문 사용)
"""

data=[2, 7, 2, 4, 6]

max = data[0]
for i in data:
  if i> max:
    max=i
print(max)

"""##### min()을 사용하지 않고 min() 구현하기(for 문 사용)"""

data=[2, 7, 2, 4, 6]

min = data[0]
for i in data:
  if min > i:
    min = i
print(min)

"""##### sum()을 사용하지 않고 sum()  구현하기(for 문 사용)"""

data=[2, 7, 2, 4, 6]

sum = 0
for i in data:
  sum+=i
print(sum)

"""##### 평균값 구현하기(for 문 사용)"""

data=[2, 7, 2, 4, 6]

mean = 0
for i in data:
  mean+=i
print(mean/len(data))